#!/bin/sh

echo "Waiting for host..." >&2

touch /tmp/.wait-for-host
for i in $(seq 1 10); do
    if ! [ -e /tmp/.wait-for-host ]; then
        break
    fi
    sleep 1
done
if [ -e /tmp/.wait-for-host ]; then
    echo "Timed out waiting for host." >&2
    exit 1
fi


# set up radio
phy="$(ls /sys/class/ieee80211/ | head -n 1)"
uci batch <<EOF

add wireless.radio0 wifi-device
set wireless.radio0.type="mac80211"
set wireless.radio0.phy="${phy}"
set wireless.radio0.band="5g"

commit wireless
EOF

# set up LED
name="jk-$(cat /etc/hostname)"
uci batch <<EOF

add system.led_power led
set system.led_power.name="Power"
set system.led_power.sysfs="${name}:green:power"
set system.led_power.trigger="none"
set system.led_power.default=1

add system.led_lan led
set system.led_lan.name="LAN"
set system.led_lan.sysfs="${name}:green:lan"
set system.led_lan.trigger="netdev"
set system.led_lan.dev="eth0"
set system.led_lan.mode="link tx rx"

add system.led_wan led
set system.led_wan.name="WAN"
set system.led_wan.sysfs="${name}:green:wan"
set system.led_wan.trigger="netdev"
set system.led_wan.dev="eth1"
set system.led_wan.mode="link tx rx"

add system.led_wlan led
set system.led_wlan.name="WLAN"
set system.led_wlan.sysfs="${name}:green:wlan"
set system.led_wlan.trigger="${phy}tpt"

commit system
EOF
